<?php
echo
'<meta name="title" content="Pawesome Pet Services">
<meta name="description" content="Servicing North Brisbane, we offer Hydrobath, Dog Walking, Pet Sitting & Furniture services that are sure to make your pet\'s day totally pawesome!">
<meta property="og:type" content="website">
<meta property="og:url" content="https://pawesomepet/">
<meta property="og:title" content="Pawesome Pet Services">
<meta property="og:description" content="Servicing North Brisbane, we offer Hydrobath, Dog Walking, Pet Sitting & Furniture services that are sure to make your pet\'s day totally pawesome!">
<meta property="og:image" content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">
<meta property="twitter:card" content="summary_large_image">
<meta property="twitter:url" content="https://metatags.io/">
<meta property="twitter:title" content="Pawesome Pet Services">
<meta property="twitter:description" content="Servicing North Brisbane, we offer Hydrobath, Dog Walking, Pet Sitting & Furniture services that are sure to make your pet\'s day totally pawesome!">
<meta property="twitter:image" content="https://metatags.io/assets/meta-tags-16a33a6a8531e519cc0936fbba0ad904e52d35f34a46c97a2c9f6f7dd7d336f2.png">';
?>